### ISSUE TITLE
Setup proper code coverage with source maps 

### ISSUE THREAD

**Issue by igor-ka** [rangle/angular-redux-starter#2] opened 2015-11-13 17:35 UTC
In es6 world the setup for unit test coverage is achieved by a combination of source maps, karma-coverage as well as istanbul-instrumenter.

This does not seem to work when typescript loader in used in conjunction with webpack.

**Comment by SethDavenport** [comment] 2016-01-27 14:54
I'm tracking all starter issues in the merged ZenHub board.  Issues are labelled according to the starters they affect.

https://github.com/rangle/react-redux-starter#boards?repos=45710306,46129075,49850682,48808013,49800398

**Comment by SethDavenport** [comment] 2016-01-27 14:54
Therefore, I'm marking this as a duplicate of https://github.com/rangle/angular2-redux-starter/issues/2.

**Closed by SethDavenport** 2016-01-27 14:54 UTC
Labels: duplicate
